# Generated by Django 5.2.4 on 2025-07-24 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Listing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("external_id", models.IntegerField()),
                ("datetime", models.DateTimeField()),
                ("platform", models.CharField()),
                (
                    "type",
                    models.CharField(
                        choices=[("BUY", "buy"), ("SELL", "sell")], null=True
                    ),
                ),
                ("amount", models.FloatField()),
                ("recipient_details", models.CharField()),
                ("currency", models.CharField(null=True)),
                ("bank", models.CharField()),
                ("currency_rate", models.FloatField(null=True)),
                ("link", models.CharField()),
            ],
        ),
    ]
