# Generated by Django 5.2.4 on 2025-07-24 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Platform",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Название")),
                (
                    "code",
                    models.CharField(max_length=50, verbose_name="Кодовое название"),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="listing",
            name="platform",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="listings.platform",
                verbose_name="Платформа",
            ),
        ),
    ]
