# Generated by Django 5.2.4 on 2025-07-25 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0002_platform_alter_listing_platform"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="platform",
            field=models.CharField(),
        ),
    ]
