# Generated by Django 5.2.4 on 2025-07-25 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0004_alter_listing_external_id"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="listing",
            constraint=models.UniqueConstraint(
                fields=("external_id",), name="unique_external_id"
            ),
        ),
    ]
